### ISSUE TITLE
Plans/direction for using Rhai?

### ISSUE THREAD

**Issue by dragonnn** [PolyMeilex/Anodium#1]
Hi!
Last few days I have be playing with using Rhai inside Smithay Anvil example WM, then I stumbled across repo and saw you are also doing something with using Rhai.
Do you have plans to extended what Rhai scripts can do in your WM?
My goal is to recreate awesome wm experience using Rhai instead of LUA so I am looking for something with allows doing most of WM logic inside scripts.
But I feel In some spaces programming skills are too low too do this.
Maybe I could try doing some PR to extended what Rhai can do in your WM?
In anvil for example I got working keyboard bindings via script:
```
log::info("initalizing!!!");

keyboard::register(|| {
    log::info("key called P");
}, "Super_L", ["p"]);

keyboard::register(|| {
    log::info("key called H");
}, "Super_L", ["h"]);

keyboard::register(|| {
    log::info("starting weston terminal");
    system::exec("weston-terminal");
}, "Super_L", ["t"]);
```
It passes callback functions inside the Rust engine with then are called when a keyboard press occurs.

**Comment by PolyMeilex** [comment]
I'm still not sure if I'll go with rhai, but it seems like a cool way to handle configuration of the conpositor so I'm using it for now, I doubt I will go AwesomeWM route, mostly because building  uncustomizable compositor (especially with rust) is already a suicide mission, so ideally I'd like to keep a scope of the project to minimum, so I can hopefully get at least usable compositor in my lifetime 😅

In scope of my rhai config (If I end up using rhai) are:
- Keyboard shortcuts 
- Workspace configuration 
- Output configuration
- Input configuration
- Autostart/exec stuff 

It would also be cool to create custom layouts in rhai, but like I said I would prefer to get the buildin layouts to usable state first.

**Comment by dragonnn** [comment]
Yeah I definitely agree that is "a suicide mission" :sweat_smile:.
I am perfectly fine with starting small :D, buildin layouts definitely should be first.
What do you think about my approach for keyboard bindings? I think I should be able to port it to Anodium.

**Comment by PolyMeilex** [comment]
Yeah, something like that would be a great starting point, current shortcut handler is just copy-pasted from anvil, so it has to be replaced with a customizable approach anyway. 
So yeah, if you want, feel free to work on that.

If you have any questions, I'm usually active in Smithay's chatroom on matrix [#smithay:matrix.org](https://matrix.to/#/#smithay:matrix.org)
If it's something less Smithay related, you can also DM me at [@poly_meilex:matrix.org](https://matrix.to/#/@poly_meilex:matrix.org) or `Poly#1945` on Discord
