### ISSUE TITLE
[Question] compile and first impression.

### ISSUE THREAD

**Issue by ahmadraniri1994** [PolyMeilex/Anodium#20]
Honestly, I kinda hate rust, sometimes it downloads huge data when compile stuffs (I have limitted and slow internet), how to build / compile this wayland compositor ? Thanks.

**Comment by ahmadraniri1994** [comment]
it's kind of solved.
I run this : 
`$ cargo build`
`$ cargo install --path .`

**Comment by ahmadraniri1994** [comment]
I run `$PATH/anodium -b winit` but not lauch, `$PATH/anodium` launch the compositor. Some wayland native apps not working (fuzzel, wofi).

**Comment by ahmadraniri1994** [comment]
Press ESC key kills session instantly,  I'm a vim user, so ESC key is vital.
Also, the example configuration is too minimal.

**Comment by PolyMeilex** [comment]
Anodium is not a usable compositor, it's super WIP, and the main point atm is to test out smithay liblary used to write wayland compositors in rust. So most of my time is spent helping with smithay instead, as I believe that having a solid base for anyone to build upon is more important. Obviously the end goal is to write a usable compositor here, but just not the priority now.

Esc is intentionally super simple key, in order to maximize the chance of it working during testing, less complexity etc. I'm also a vim user so I have it binded to caps so it's super easy and fast to press and go back to editing the code. Real compositor will not close on you if you press a random button, it will be a part of configuration like anything else. The only hardcoded keys will be tty switch keys, for the same reason, that's the last thing I would like to not work, anything beyond that will be just a shortcut.

So for Rust, end users will never compile compositor themselves, unless they are using an exotic distro that forces them to compile all software manually, I doubt you are one of those users if you have bad internet connection, but yeah that assumes that the project is usable thing ready for packaging, but it's not atm.

Thanks for interest anyway!

**Comment by ahmadraniri1994** [comment]
Thanks for replying @PolyMeilex , I'm interested with this project, I'm trying some Wayland compositors (e.g sway, labwc, dwl, etc).
Once more, do you mind to share your configuration or where do I look for actions / functions (e.g. resize, move, etc) ? Thanks.
I hope this project will become great.

**Comment by ahmadraniri1994** [comment]
Well, Better to stick to proper wayland compositor then.
